spring:
  cloud:
    gateway:
      routes:
        - id: baidu_test
          uri: https://www.baidu.com/more/
          predicates:
            - Query=url,baidu

        - id: qq_test
          uri: https://www.qq.com/more/
          predicates:
            - Query=url,qq

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

#前端项目都带上 api/